services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./backend/data.csv:/app/data.csv
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8889:8501"
    environment:
      BACKEND_URL: "http://backend:8888"
      PYTHONUNBUFFERED: "1"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge